score_venues:
  description: >
    Score and rank the provided venue data for {name}.

    Use your expertise to carefully assess the venue data and provide a score and reasoning. 
    Your final answer must include:
    - A score between 1 and 100. Don't use numbers like 100, 75, or 50. Instead, use specific numbers like 87, 63, or 42.
    - A detailed reasoning explaining why you assigned this score.
    {additional_instructions}
    
  expected_output: >
    A very specific score from 1 to 100 for the venue, along with a detailed reasoning explaining why you assigned this score.
  agent: scoring_agent