send_followup_email:
  description: >
    Generate professional outreach emails for top-scoring venues and save them to the 'emails' folder.

    You will use the venue's name, and the features that were extracted to generate the email.

    VENUE DETAILS
    -----------------
    Venue ID: {venue_id}
    Name: {name}
    Special Features: {special_features}

  expected_output: >
    A professional outreach email to the venue. 
  agent: email_followup_agent
