send_followup_email:
  description: >
    Generate professional outreach emails for top-scoring venues and save them to the 'emails' folder.

    You will use the venue's name, address, and the features that were extracted to generate the email using the following template.

    EMAIL TEMPLATE
    -----------------
    {email_template}

  expected_output: >
    A professional outreach email based on the venue's data and the email template. 
  agent: email_followup_agent