analyze_location:
  description: "Search for venues within {input_data[radius_km]}km of {input_data[address]}"
  expected_output: >
    List of potential venues with details
  context: []
  agent: "location_analyst"

# extract_features:
#   description: >
#     Extract features from identified venues
#   expected_output: >
#     Detailed venue features
#   context: ["analyze_location"]
#   agent: "feature_extractor"

# score_venues:
#   description: >
#     Score and rank venues based on features
#   expected_output: >
#     Venue scores and rankings
#   context: ["extract_features"]
#   agent: "scoring_agent"

# generate_emails:
#   description: >
#     Generate professional outreach emails for top-scoring venues and save them to the 'emails' folder.

#     If a custom email template is provided in {input_data[email_template]}, use it exactly as specified.
#     Otherwise, use the default professional email format that includes:
#     - Proper business email greeting
#     - Introduction and purpose
#     - Highlight of venue's key features and total score
#     - Specific areas of interest based on venue analysis
#     - Professional closing
#     - Sender details

#     The email should maintain a professional tone while emphasizing the venue's unique strengths
#     identified during scoring. Include relevant details about capacity, amenities, and location
#     advantages that were noted during venue analysis.

#   expected_output: >
#     {
#       "venue_id": str,
#       "recipient": str, 
#       "subject": str,
#       "body": str,
#       "follow_up_date": str,
#       "venue_score": float,
#       "key_features": str
#     }
#   context: ["score_venues"]
#   agent: "email_agent"

# generate_report:
#   description: >
#     Create final analysis report and save it to the 'generated_reports' folder
#     with timestamp. Include comprehensive venue analysis, scoring details,
#     and references to generated emails.
#   expected_output: >
#     Path to generated report file and summary of findings
#   context: ["generate_emails"] 
#   agent: "reporting_agent"
