analyze_location:
  description: "Search for venues within {input_data[radius_km]}km of {input_data[address]}"
  expected_output: >
    List of potential venues with details
  context: []
  agent: "location_analyst"

extract_features:
  description: >
    Extract features from identified venues
  expected_output: >
    Detailed venue features
  context: ["analyze_location"]
  agent: "feature_extractor"

score_venues:
  description: >
    Score venues based on features
  expected_output: >
    Venue scores and rankings
  context: ["extract_features"]
  agent: "scoring_agent"

generate_emails:
  description: >
    Generate outreach emails for top venues and save them to the 'generated_emails' folder.
    Each email should be saved as a separate file with the venue name.
  expected_output: >
    List of generated email paths and their metadata
  context: ["score_venues"]
  agent: "email_agent"

generate_report:
  description: >
    Create final analysis report and save it to the 'generated_reports' folder
    with timestamp. Include comprehensive venue analysis, scoring details,
    and references to generated emails.
  expected_output: >
    Path to generated report file and summary of findings
  context: ["generate_emails"] 
  agent: "reporting_agent"
