analyze_location:
  description: >
    Search for restaurants, hotels, event spaces, banquet halls, conference centers, and venues within {input_data[radius_km]}km of {input_data[address]}. Include both large and small venues, and don't exclude any based on ratings or reviews. Look for places that can host events or gatherings.
  expected_output: >
    List of potential venues with details
  agent: "location_analyst"